### ISSUE TITLE
Uploading aab failed a second time

### ISSUE THREAD

**Issue by jcalixte** [bamlab/flashlight#207]
```bash
flashlight cloud --app packages/expo/build-1709631846799.aab --test packages/expo/e2e/perf.yml --duration 60000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 27.6M  100 27.6M    0     0  3944k      0  0:00:07  0:00:07 --:--:-- 4952k
[BT:1.14.0] Error: File 'myapp.apks' already exists.
java.lang.IllegalArgumentException: File 'myapp.apks' already exists.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at com.android.tools.build.bundletool.model.utils.files.FilePreconditions.checkFileDoesNotExist(FilePreconditions.java:30)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.validateInput(BuildApksCommand.java:947)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:888)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:83)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
[11:26:45] ℹ️  Logging in...
```

Step to reproduce: launching twice the command.

Others artefacts are always there:

- bundletools.jar
- /apks folder
- and myapp.apks

**Comment by Almouro** [comment]
This is fixed in v0.17.1! 🥳

To upgrade: `curl -Ls "https://get.flashlight.dev/" | bash`
