### ISSUE TITLE
--skipRestart is causing issue, test runs not getting completed

### ISSUE THREAD

**Issue by dipak-amber** [bamlab/flashlight#297]
flashlight test \
  --bundleId com.amberstudent \
  --beforeAllCommand "maestro test /users/dipakkorde/desktop/AppPerfScripts1/SetupHomeToSearch.yml" \
  --testCommand "maestro test /users/dipakkorde/desktop/AppPerfScripts1/NavHomeToSearch.yml" \
  --resultsFilePath /users/dipakkorde/desktop/results/resulthometosearch.json \
  --skipRestart

**While running tests using this runs not getting completed. Getting error**

/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/atrace/pollFpsUsage.js:11
            throw new Error(`Could not parse ATrace line "${line}"`);
            ^

Error: Could not parse ATrace line "CPU:2 [LOST 1457 EVENTS]"
    at parseLine (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/atrace/pollFpsUsage.js:11:19)
    at FrameTimeParser.getFrameTimes (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/atrace/pollFpsUsage.js:75:105)
    at /snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/pollPerformanceMeasures.js:30:74
    at /snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/cppProfiler.js:48:9
    at /snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/shell.js:84:13
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/shell.js:83:33)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)

Node.js v18.5.0

Instead when i am running tests using

flashlight test \                                                          
  --bundleId com.amberstudent \
  --beforeAllCommand "maestro test /users/dipakkorde/desktop/AppPerfScripts/SetupFlow.yml" \
  --testCommand "maestro test /users/dipakkorde/desktop/AppPerfScripts/ScrollSearchPage.yml" \
  --resultsFilePath /users/dipakkorde/desktop/results/resulthometosearch.json

All iterations getting completed.

**Comment by Almouro** [comment]
@dipak-amber this might have been mitigated with #295, can you try again with the latest `flashlight`?

You should be able to upgrade with `curl https://get.flashlight.dev | bash`
