### ISSUE TITLE
Flashlight CLI crashes locally using Android 10 devices with release app

### ISSUE THREAD

**Issue by anton-patrushev** [bamlab/flashlight#307]
I just followed `README` and downloaded `flashlight@18.0.0`

I tried to run `flashlight measure` and it successfully launched the local web app on the  `localhost:3000`
I also can successfully fetch the `Auto Detect` app bundle id.

But as soon as I press on `Start Measuring` — it fails in the CLI and shows an alert:
Here is my CLI log:
```
➜  ~ flashlight measure
[13:54:21] ℹ️  Installing C++ profiler for arm64-v8a architecture
[13:54:21] ✅  C++ Profiler installed in /data/local/tmp/BAMPerfProfiler

 Flashlight web app running on: http://localhost:3000

/snapshot/flashlight-cloud/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Command failed: adb shell atrace --async_stop
    at checkExecSyncError (node:child_process:820:11)
    at Object.execSync (node:child_process:891:15)
    at execSync (pkg/prelude/bootstrap.js:2111:30)
    at AndroidProfiler.startATrace (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/platforms/AndroidProfiler.js:62:38)
    at AndroidProfiler.installProfilerOnDevice (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/platforms/AndroidProfiler.js:28:18)
    at AndroidProfiler.getCpuClockTick (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/platforms/UnixProfiler.js:95:14)
    at AndroidProfiler.pollPerformanceMeasures (/snapshot/flashlight-cloud/flashlight-open-source/packages/platforms/android/dist/src/commands/platforms/UnixProfiler.js:123:90)
    at PerformanceMeasurer.<anonymous> (/snapshot/flashlight-cloud/flashlight-open-source/packages/commands/test/dist/PerformanceMeasurer.js)
    at Generator.next (<anonymous>) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 5608,
  stdout: null,
  stderr: null
}

Node.js v18.5.0
➜  ~
```

And this is a pretty generic alert I see in the web app
<img width="650" alt="image" src="https://github.com/user-attachments/assets/a2d86bb9-0b72-414a-b9dc-a8fc6d8ee325">

I found one similar issue in this repo, but I think:
1. it's a pretty old one since I'm not using Flipper (and I can't) since I need to have a connection to the `Release` app.
2. it's not relevant to me, more info below

Here is the issue link: https://github.com/bamlab/flashlight/issues/103

I tried a few suggestions from that issue, and here is my results:
```
➜  ~ adb devices
List of devices attached
a7276a2c	device

➜  ~ ps | grep "adb shell"
 5699 ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox adb shell
➜  ~ adb shell atrace --async_stop
Error: Did not find trace folder
No trace folder found
➜  ~
```

**Comment by anton-patrushev** [comment]
@Almouro would you be able to take a look 🙏 ?

**Comment by Almouro** [comment]
Hi @anton-patrushev, that's quite weird!

The error seems to be coming from [here in the Android source code](https://android.googlesource.com/platform/frameworks/native/+/master/cmds/atrace/atrace.cpp#1131)
It checks for one of those folders:
- `/sys/kernel/debug/tracing/`
- `/sys/kernel/tracing/`

What's your device model and Android version?

**Comment by anton-patrushev** [comment]
it's a pretty old and custom one 😅

Model: Xiaomi Redmi Note 5
Android OS: 10

But it has a custom OS since I reset MIUI and re-install a Pixel-like OS on this device 😅 

Does it make sense to try to connect this device to the Android Studio profiler and see if it's a device-specific issue or a Flashlight edge case?

cc: @Almouro

**Comment by Almouro** [comment]
Hmm the fact that it's custom might be why indeed 🤔

We only use `atrace` to measure FPS, so I'm not sure if Android Studio profiler uses it, you could try running a system trace from "Profiler" > Click on CPU graph > Record system trace

I'm guessing running a trace with [Perfetto](https://ui.perfetto.dev/#!/record/instructions) would fail as well
